version: '3.8'
services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_RUBY_VERSION: 3.1.2
      context: .
    working_dir: /home/user/technical_challenge_02
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/technical_challenge_02
volumes:
  app_local:
